/*
  ----------------------------------------------------
    DO NOT EDIT THIS FILE! IF YOU ARE EDITING REACT SRC
    YOU ARE NOT DOING THIS PROBLEM CORRECTLY!
  ----------------------------------------------------
*/
import React, { useState, useEffect } from 'react';
import { FaTrash } from 'react-icons/fa';
import './App.css';
import axios from 'axios'

function App() {

  const [ todo, setTodo ] = useState([])
  const [ input, setInput ] = useState([])
  useEffect(() => {
    async function getTodos(){
      axios.get('/api/todos')
      .then(res => setTodo(res.data))
      .catch(err => { console.log(err); setTodo([])})
    }
    getTodos()
  }, [])

  function addTodo(content) {
    axios.post('api/todos', { completed: false, content })
    .then(res => setTodo(res.data))
    .catch(err => { console.log(err); setTodo([])})
  }
  function updateComplete(index, comp) {
    axios.patch(`/api/todos/${index}`, { completed: comp })
    .then(res => setTodo(res.data))
    .catch(err => { console.log(err); setTodo([])})
  }
  function deleteTodo(index) {
    axios.delete(`/api/todos/${index}`)
    .then(res => setTodo(res.data))
    .catch(err => { console.log(err); setTodo([])})
  }

  const todoList = todo.map((td, i) => (
    <div className='todo' key={i}>
      <input type='checkbox' checked={td.completed} onChange={() => updateComplete(i, !td.completed)} />
      <h1 style={td.completed ? {textDecoration: 'line-through'} : {}}>{td.content}</h1>
      <FaTrash onClick={() => deleteTodo(i)}/>
    </div>
  ))

  return (
    <div className="App">
      <header className="App-header">
       To Do List
      </header>
      <div className='form'>
        <input value={input} onChange={e => setInput(e.target.value)}/>
        <button onClick={() => { addTodo(input); setInput('')}}>Add</button>
      </div>
      <div className='todo-container'>
        {todoList}
      </div>
    </div>
  );
}

export default App;
